// THIS IS AN AUTOGENERATED FILE PLEASE DO NOT MODIFY MANUALLY
export enum SchemaDefinition {
    SCHEMADEFINITION = "#/definitions/SchemaDefinition",
    SIMPLESCHEMA = "#/definitions/SimpleSchema",
}