// THIS IS AN AUTOGENERATED FILE PLEASE DO NOT MODIFY MANUALLY
export enum SchemaDefinition {
    MOCKTYPE = "#/definitions/MockType",
    SIMPLESCHEMA = "#/definitions/SimpleSchema",
    SOCKTYPE = "#/definitions/SockType",
    SOMEENUM = "#/definitions/SomeEnum",
}
